//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFElevInterview {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RessourceFil {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RessourceFil() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GFElevInterview.RessourceFil", typeof(RessourceFil).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballerup.
        /// </summary>
        internal static string ballerup {
            get {
                return ResourceManager.GetString("ballerup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brugervejledning - Leder.pdf.
        /// </summary>
        internal static string brugVejLeder {
            get {
                return ResourceManager.GetString("brugVejLeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brugervejledning.
        /// </summary>
        internal static string brugVejMappe {
            get {
                return ResourceManager.GetString("brugVejMappe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brugervejledning - Underviser.pdf.
        /// </summary>
        internal static string brugVejUnderviser {
            get {
                return ResourceManager.GetString("brugVejUnderviser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elevDB.db.
        /// </summary>
        internal static string db {
            get {
                return ResourceManager.GetString("db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _M.pdf.
        /// </summary>
        internal static string endMerit {
            get {
                return ResourceManager.GetString("endMerit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _RKV.pdf.
        /// </summary>
        internal static string endRKV {
            get {
                return ResourceManager.GetString("endRKV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frederiksberg.
        /// </summary>
        internal static string frederiksberg {
            get {
                return ResourceManager.GetString("frederiksberg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GF2 -.
        /// </summary>
        internal static string gfTitle {
            get {
                return ResourceManager.GetString("gfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastruktur.
        /// </summary>
        internal static string infrastruktur {
            get {
                return ResourceManager.GetString("infrastruktur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT-supporter.
        /// </summary>
        internal static string itsupporter {
            get {
                return ResourceManager.GetString("itsupporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyngby.
        /// </summary>
        internal static string lyngby {
            get {
                return ResourceManager.GetString("lyngby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merit-blanket.docx.
        /// </summary>
        internal static string meritBlanketDoc {
            get {
                return ResourceManager.GetString("meritBlanketDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string minimumGrundforløbLængde {
            get {
                return ResourceManager.GetString("minimumGrundforløbLængde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\Blanketter.
        /// </summary>
        internal static string outputMappe {
            get {
                return ResourceManager.GetString("outputMappe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blanketter.
        /// </summary>
        internal static string outputMappeNavn {
            get {
                return ResourceManager.GetString("outputMappeNavn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmering.
        /// </summary>
        internal static string programmering {
            get {
                return ResourceManager.GetString("programmering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PyExcel\\GFExcel.exe.
        /// </summary>
        internal static string pythonScript {
            get {
                return ResourceManager.GetString("pythonScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\Blanketter\\_Samlet Merit.pdf.
        /// </summary>
        internal static string samletMerit {
            get {
                return ResourceManager.GetString("samletMerit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\Blanketter\\_Samlet RKV.zip.
        /// </summary>
        internal static string samletRKV {
            get {
                return ResourceManager.GetString("samletRKV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuldt forløb.
        /// </summary>
        internal static string skoleIngenMerit {
            get {
                return ResourceManager.GetString("skoleIngenMerit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinær+.
        /// </summary>
        internal static string skoleMerit {
            get {
                return ResourceManager.GetString("skoleMerit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bal;fre;lyn;balP;balF.
        /// </summary>
        internal static string skolerDictKey {
            get {
                return ResourceManager.GetString("skolerDictKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to root.
        /// </summary>
        internal static string standardPassword {
            get {
                return ResourceManager.GetString("standardPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blanketter\\Templates\\.
        /// </summary>
        internal static string templates {
            get {
                return ResourceManager.GetString("templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ved ikke.
        /// </summary>
        internal static string vedIkke {
            get {
                return ResourceManager.GetString("vedIkke", resourceCulture);
            }
        }
    }
}
